bounds:
  x: [0, 60] # x-bounds
  y: [0, 60] # y-bounds
  z: [0, 60] # z-bounds
  
initial_configuration: 
  # 4 drones
  - [1, 1, 1]
  - [2, 1, 1]
  - [3, 1, 1]
  - [4, 1, 1]
  # 8 drones
  - [5, 1, 1]
  - [6, 1, 1]
  # - [7, 1, 1]
  # - [8, 1, 1]
  # 12 drones
  # - [9, 1, 1]
  # - [10, 1, 1]
  # - [11, 1, 1]
  # - [12, 1, 1]


obstacles:
  - type: box
    position: [10, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red
    
  - type: cylinder
    endpoints: [[15, 10, 0], [15, 10, 15]] # The 3D endpoints of the cylinder
    radius: 2.5 # The radius of the cylinder in meters
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [5, 10, 2]
    radius: 2.0 # The radius of the sphere in meters
    color: red

  - type: box
    position: [18, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red

  - type: box
    position: [30, 20, 0] # The 3D position of the obstacle in the environment
    size: [6, 8, 3] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 30]  # Euler angles in degrees
    color: red

  - type: box
    position: [20, 28, 18] # The 3D position of the obstacle in the environment
    size: [10, 10, 10] # The side lengths of the box-shaped obstacle
    rotation: [0, 45, 45]  # Euler angles in degrees
    color: red

  - type: cylinder
    endpoints: [[25, 8, 10], [25, 18, 25]] # The 3D endpoints of the cylinder
    radius: 5 # The radius of the cylinder in meters
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [10, 10, 20]
    radius: 6 # The radius of the sphere in meters
    color: red

  
    
goals:
# for 4 drones
  - position: [10, 40, 5] # The 3D position of the first goal
    radius: 1.0 # The radius of the first goal
  - position: [15, 40, 5] # The 3D position of the second goal
    radius: 1.0 # The radius of the second goal
  - position: [20, 40, 5] # The 3D position of the third goal
    radius: 1.0 # The radius of the third goal
  - position: [25, 40, 5] # The 3D position of the fourth goal
    radius: 1.0 # The radius of the fourth goal
# for 8 drones
  - position: [30, 40, 5] # The 3D position of the first goal
    radius: 1.0 # The radius of the first goal
  - position: [35, 40, 5] # The 3D position of the second goal
    radius: 1.0 # The radius of the second goal
  # - position: [40, 40, 5] # The 3D position of the third goal
  #   radius: 1.0 # The radius of the third goal
  # - position: [45, 40, 5] # The 3D position of the fourth goal
  #   radius: 1.0 # The radius of the fourth goal
# for 12 drones
  # - position: [20, 50, 5] # The 3D position of the fifth goal
  #   radius: 1.0 # The radius of the fifth goal
  # - position: [25, 50, 5] # The 3D position of the sixth goal
  #   radius: 1.0 # The radius of the sixth goal
  # - position: [30, 50, 5] # The 3D position of the seventh goal
  #   radius: 1.0 # The radius of the seventh goal 
  # - position: [35, 50, 5] # The 3D position of the eighth goal
  #   radius: 1.0 # The radius of the eighth goal





  
